- hosts: all
  become:
    true
  roles:
    - role: common
    - role: letsencrypt
    - role: nginx
    - role: amplify
    - role: nat
    - role: manala.logrotate
      manala_logrotate_configs:
        - file: nginx
          config:
            - /var/log/nginx/*.log:
              - size: 100M
              - missingok
              - rotate: 5
              - compress
              - delaycompress:
              - notifempty
              - create: 0640 www-data adm
              - sharedscripts 
              - daily
              - postrotate
                  systemctl reload nginx.service
              - endscript
    - role: jnv.unattended-upgrades
      unattended_mail: notify@setevoy.kiev.ua
      unattended_automatic_reboot: true
      unattended_automatic_reboot_time: 05:00
      unattended_clean_interval: 10
