PS1='\t \[[\e[0;COLORm\]\u\[\e[m\]@\e[0;37m\]\h\[\e[m\] \[\e[1;34m\]\w\[\e[m\]]\[\e[0;31m\] \$\[\e[m\]\[\e[0;37m\] '

export EDITOR=vim

# aliases
alias osupgrade="sudo apt-get update && sudo apt-get upgrade"
