- name: Update sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#net.ipv4.ip_forward=1$'
    line: 'net.ipv4.ip_forward=1'

- name: Reload sysctl
  command: sysctl -p

- name: Iptables POSTROUTING append
  iptables:
    table: nat
    chain: POSTROUTING
    source: 10.0.0.0/16
    destination: 0.0.0.0/0
    jump: MASQUERADE

