- name: Update sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#net.ipv4.ip_forward=1$'
    line: 'net.ipv4.ip_forward=1'

- name: Reload sysctl
  command: sysctl -p

- name: Iptables POSTROUTING append
  iptables:
    table: nat
    chain: POSTROUTING
    source: 10.0.0.0/16
    destination: 0.0.0.0/0
    jump: MASQUERADE

- name: Create IPTABLES config dir
  file: path=/etc/iptables state=directory

- name: Save IPTABLES rules
  shell: "iptables-save > /etc/iptables/iptables.rules"

- name: Create systemd-service iptables dir
  file: path=/usr/lib/systemd/system state=directory

- name: Copy IPTABLES systemd-file
  copy:
    src: files/iptables.service
    dest: /usr/lib/systemd/system/iptables.service

- name: IPTABLES enable
  command: systemctl enable iptables.service
