- name: Create "{{ data_volume_mount_path }}" directory
  file:
    path: "{{ data_volume_mount_path }}"
    state: directory
    mode: 0755
    recurse: yes

- name: Mount data-volume "{{ data_volume_id }}" to "{{ data_volume_mount_path }}"
  mount:
    path: "{{ data_volume_mount_path }}"
    src: "{{ data_volume_id }}"
    state: mounted
    fstype: ext4

- name: Install common packages
  apt: name={{item}} state=present
  with_items:
       - mailutils
       - curl

- name: Set hostname
  hostname:
    name: "{{ set_hostname }}"

- name: Add hostnams to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: "127.0.0.1 localhost {{ set_hostname }} {{ inventory_hostname }}"
    state: present

- name: Update /etc/cloud/cloud.cfg.d/01_debian_cloud.cfg
  lineinfile:
    dest: /etc/cloud/cloud.cfg.d/01_debian_cloud.cfg
    regexp: '^manage_etc_hosts: true'
    line: "manage_etc_hosts: false"
    state: present

- name: Add restart notify script
  template:
    src=templates/reboot_notify.sh.j2
    dest=/usr/local/bin/reboot_notify.sh

- name: Changing reboot_notify.sh permissions
  file: 
    dest: /usr/local/bin/reboot_notify.sh
    mode: u+x

- name: Copy restart notify systemd file
  copy:
    src: files/reboot-notify.service
    dest: /usr/lib/systemd/system/reboot-notify.service

- name: Systemd enable restart notifications
  systemd:
    name: reboot-notify
    enabled: yes
