- name: Create "{{ data_volume_mount_path }}" directory
  file:
    path: "{{ data_volume_mount_path }}"
    state: directory
    mode: 0755
    recurse: yes

- name: Mount data-volume "{{ data_volume_id }}" to "{{ data_volume_mount_path }}"
  mount:
    path: "{{ data_volume_mount_path }}"
    src: "{{ data_volume_id }}"
    state: mounted
    fstype: ext4

- name: Install common packages
  apt: name={{item}} state=present
  with_items:
       - mailutils
       - curl
       - dnsutils

- name: Set hostname
  hostname:
    name: "{{ set_hostname }}"

- name: Add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: "127.0.0.1 localhost {{ set_hostname }} {{ inventory_hostname }}"
    state: present

- name: Update /etc/cloud/cloud.cfg.d/01_debian_cloud.cfg
  lineinfile:
    dest: /etc/cloud/cloud.cfg.d/01_debian_cloud.cfg
    regexp: '^manage_etc_hosts: true'
    line: "manage_etc_hosts: false"
    state: present

- name: Add restart notify script
  template:
    src=templates/reboot_notify.sh.j2
    dest=/usr/local/bin/reboot_notify.sh

- name: Change reboot_notify.sh permissions
  file: 
    dest: /usr/local/bin/reboot_notify.sh
    mode: u+x

- name: Create systemd-services dir
  file: path=/usr/lib/systemd/system state=directory

- name: Copy restart notify systemd file
  copy:
    src: files/reboot-notify.service
    dest: /usr/lib/systemd/system/reboot-notify.service

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: Systemd enable restart notifications
  systemd:
    name: reboot-notify
    enabled: yes

- name: Copy .bashrc to root
  copy:
    src: files/bashrc
    dest: /root/.bashrc

- name: Set username color in /root/.bashrc
  replace:
    path: /root/.bashrc
    regexp: 'COLOR'
    replace: '31'

- name: Copy .bashrc to admin
  copy:
    src: files/bashrc
    dest: /home/admin/.bashrc

- name: Set username color in /home/admin/.bashrc
  replace:
    path: /home/admin/.bashrc
    regexp: 'COLOR'
    replace: '32'

- name: Copy .vimrc to root
  copy:
    src: files/vimrc
    dest: /root/.vimrc

- name: Copy .vimrc to admin
  copy:
    src: files/vimrc
    dest: /home/admin/.vimrc

- name: Set timezone to Europe/Kiev
  timezone:
    name: Europe/Kiev

- name: Change root mailbox
  lineinfile:
    dest: /etc/aliases
    regexp: '^root: '
    line: "root: {{ notify_email }}"
    state: present
 
- name: Update mail aliases
  shell:
    newaliases
